CREATE SCHEMA Prog2;

USE Prog2;

CREATE TABLE usuarios (
	id_usuario			INT 				UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	email 				VARCHAR(250) 		NOT NULL,
    contrasenas 		VARCHAR(250)		NOT NULL, 
    fecha 				DATE 				NOT NULL,
    DNI 				INT 				NOT NULL,
    foto 				VARCHAR(250) 		NOT NULL,
    createdAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP,
    updatedAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE productos (
	id_producto			INT 				UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    id_usuario 			INT 				UNSIGNED,
	imagenProducto 		VARCHAR(250) 		NOT NULL,
    nombreProducto 		VARCHAR(250)		NOT NULL, 
    descripcion 		VARCHAR(400) 		NOT NULL,
    createdAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP,
    updatedAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    
);

CREATE TABLE comentarios (
	id_comentario		INT 				UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    id_usuario 			INT					UNSIGNED,
	id_producto			INT					UNSIGNED,
    comentario 		  	VARCHAR(350)		NOT NULL, 
    createdAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP,
    updatedAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
);





