CREATE SCHEMA Prog2;

USE Prog2;

CREATE TABLE usuarios (
	id_usuario			INT 				UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	email 				VARCHAR(250) 		NOT NULL,
    contrasenas 		VARCHAR(250)		NOT NULL, 
    fecha 				DATE 				NOT NULL,
    DNI 				INT 				NOT NULL,
    foto 				VARCHAR(250) 		NOT NULL,
    createdAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP,
    updatedAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt 			TIMESTAMP 			DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);